from tabarena.nips2025_utils.artifacts.method_metadata import MethodMetadata


tabstar_metadata = MethodMetadata(
    method="TabSTAR",
    method_type="config",
    display_name="TabSTAR",
    compute="gpu",
    date="2026-03-02",
    ag_key="TABSTAR",
    model_key="TABSTAR",
    config_default="TabSTAR_c1_BAG_L1",
    can_hpo=True,
    is_bag=True,
    has_raw=True,
    has_processed=True,
    artifact_name="tabarena-2026-03-18",
    s3_bucket="tabarena",
    s3_prefix="cache",
    upload_as_public=True,
    has_results=True,
    name_suffix=None,
    verified=True,
    reference_url="https://arxiv.org/abs/2505.18125",
    cache_type="r2",
)

perpetualbooster_metadata = MethodMetadata(
    method="PerpetualBooster",
    method_type="config",
    display_name="PerpetualBooster",
    compute="cpu",
    date="2026-03-06",
    ag_key="PB",
    model_key="PB",
    config_default="PerpetualBooster_c1_BAG_L1",
    can_hpo=True,
    is_bag=True,
    has_raw=True,
    has_processed=True,
    artifact_name="tabarena-2026-03-18",
    s3_bucket="tabarena",
    s3_prefix="cache",
    upload_as_public=True,
    has_results=True,
    name_suffix=None,
    verified=True,
    reference_url="https://perpetual-ml.com/",
    cache_type="r2",
)

tabpfn26_metadata = MethodMetadata(
    method="TabPFN-v2.6",
    method_type="config",
    display_name="TabPFN-2.6",
    compute="gpu",
    date="2026-03-25",
    ag_key="TABPFN-V2.6",
    model_key="TABPFN-V2.6",
    config_default="TabPFN-v2.6_c1_BAG_L1",
    can_hpo=False,
    is_bag=False,
    has_raw=True,
    has_processed=True,
    artifact_name="tabarena-2026-03-18",
    s3_bucket="tabarena",
    s3_prefix="cache",
    upload_as_public=True,
    has_results=True,
    name_suffix=None,
    verified=True,
    reference_url="https://arxiv.org/abs/2511.08667",
    cache_type="r2",
)
